name: CI jobs
on:
  push:
    branches:
      - main
      - r[0-9]+.*
  pull_request:
    branches:
      - main
      - r[0-9]+.*
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build project
        run: |
          java -version
          mvn -version
          mvn clean install -B -U -e
      - name: Deploy snapshot artifacts
        if: github.event_name == 'push' && contains(github.ref, 'main')
        run: |
          echo "<settings><servers><server><id>ossrh</id><username>${{ secrets.CI_DEPLOY_USERNAME }}</username><password>${{ secrets.CI_DEPLOY_PASSWORD }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
          mvn deploy -B -U -e -Dmaven.test.skip=true
      - name: Release artifacts
        if: github.event_name == 'push' && startsWith(github.ref, 'r')
        run: |
          echo "<settings><servers><server><id>ossrh</id><username>${{ secrets.CI_DEPLOY_USERNAME }}</username><password>${{ secrets.CI_DEPLOY_PASSWORD }}</password></server><server><id>github</id><username>${{ secrets.CI_COMMIT_USERNAME }}</username><password>${{ secrets.CI_COMMIT_PASSWORD }}</password></server></servers>\
          <profiles><profile><id>releasing</id><properties><gpg.executable>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase></properties></profile></profiles></settings>" > $HOME/.m2/settings.xml
          mvn -P releasing release:prepare -B -U -e
          mvn -P releasing release:perform -B -U -e -Dmaven.test.skip=true
